services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: tracker
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    ports:
      - "8081:8080"
    volumes:
      - ./tracker/:/app/
    restart: on-failure